source 'https://rubygems.org'
ruby '1.9.3'
gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
group :development , :test do
	gem 'sqlite3', '>=1.3.8'
	gem "mysql", '2.8.1' 
	# gem "mysql2", '0.2.18'
	#gem 'activerecord-sqlite3-adapter'
	gem "launchy"
	gem "rspec-rails", ">= 2.0.0"
	gem "cucumber-rails", ">= 0.3.2", :require => false
	gem "webrat", ">= 0.7.2"
	gem "capybara" 
	gem 'database_cleaner', github: 'bmabey/database_cleaner'
	gem "selenium-client", ">= 1.2.18"
	gem "Selenium"
	gem "selenium-webdriver", '~> 2.41.0'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '2.1.1'
end

gem 'jquery-rails', '3.0.4'
gem 'jquery-ui-rails'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger
gem 'debugger'

gem "will_paginate", '~> 3.0'

gem "RedCloth"

group :production do
	gem 'pg', '0.15.1'
	gem 'rails_12factor', '0.0.2'
end